apiVersion: v1
kind: Service
metadata:
  name: dms-fake-devices-service
  labels:
    name: dms-fake-devices-service
    app: device-monitoring-system
spec:
  type: ClusterIP
  ports:
    - port: 30004
      targetPort: 8080
  selector:
    name: dms-fake-devices-pod
    app: device-monitoring-system
