apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
  labels:
    name: rabbitmq-deploy
    app: device-monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq-pod
      app: device-monitoring-system

  template:
    metadata:
      name: rabbitmq-pod
      labels:
        name: rabbitmq-pod
        app: device-monitoring-system
    spec:
      containers:
        - name: rabbitmq
          image: masstransit/rabbitmq
          ports:
            - containerPort: 15672
              name: rabbitmq-mmgt
            - containerPort: 5672
              name: rabbitmq-amqp
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
