apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    name: rabbitmq-service
    app: device-monitoring-system
spec:
  type: ClusterIP
  ports:
    - port: 15672
      targetPort: 15672
      name: rabbitmq-mmgt
    - port: 5672
      targetPort: 5672
      name: rabbitmq-amqp
  selector:
    name: rabbitmq-pod
    app: device-monitoring-system
